[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "tauri-app"
edition = "2018"
build = "src/build.rs"

[dependencies]
dirs = "3.0.1"
serde_json = "1.0.61"
serde = { version = "1.0.118", features = [ "derive" ] }
tauri = { version = "0.11.0", features = [ "all-api" ] }
uuid = "0.8.1"
rocksdb = "0.15.0"
anyhow = "1.0.37"
oracle = { version = "0.3.3", features = [ "chrono" ] }
regex = "1.4.2"
tokio-postgres = { version = "0.7.0", features = [ "with-uuid-0_8", "with-chrono-0_4" ] }
tokio = { version = "1.0.1", features = [ "full" ] }
log = "0.4.11"
fern = "0.6.0"
chrono = "0.4.19"
glob = "0.3.0"
lazy_static = "1.4.0"
futures = "0.3.8"
sqlformat = "0.1.5"
juniper = "0.15.1"

[target."cfg(windows)".build-dependencies]
winres = "0.1.11"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "tauri-app"
path = "src/main.rs"
