[package]
name = "my-app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "my-app"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "0.9", features = [ "all-api" ] }
rocksdb = "0.14.0"
anyhow = "1.0.32"
oracle = "0.3.2"
regex = "1"
tokio-postgres = { git = "https://github.com/glistenlau/rust-postgres" }
tokio = { version = "0.2.22", features = [ "full" ] }
log = "0.4.11"
fern = "0.6.0"
chrono = "0.4.13"

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "my-app"
path = "src/main.rs"
