[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "tauri-app"
edition = "2018"
build = "src/build.rs"

[dependencies]
dirs = "3.0.1"
serde_json = "1.0.61"
serde = { version = "1.0.118", features = [ "derive" ] }
tauri = { version = "1.0.0-beta.1", features = ["api-all"] }
uuid = "0.8.1"
rocksdb = "0.16.0"
anyhow = "1.0.37"
oracle = { version = "0.5.1", features = [ "chrono" ] }
regex = "1.4.2"
tokio-postgres = { version = "0.7.0", features = [ "with-uuid-0_8", "with-chrono-0_4" ] }
tokio = { version = "1.0.1", features = [ "full" ] }
log = "0.4.11"
fern = "0.6.0"
chrono = "0.4.19"
glob = "0.3.0"
lazy_static = "1.4.0"
futures = "0.3.8"
sqlformat = "0.1.5"
juniper = "0.15.1"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.0" }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
default = [ "custom-protocol" ]

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "tauri-app"
path = "src/main.rs"
